//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.UtilityServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://webstrar.fulton.asu.edu/website142", ConfigurationName="UtilityServiceRef.UtilityServiceSoap")]
    public interface UtilityServiceSoap {
        
        // CODEGEN: Generating message contract since element name input from namespace https://webstrar.fulton.asu.edu/website142 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://webstrar.fulton.asu.edu/website142/CountCharacters", ReplyAction="*")]
        WebApplication.UtilityServiceRef.CountCharactersResponse CountCharacters(WebApplication.UtilityServiceRef.CountCharactersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webstrar.fulton.asu.edu/website142/CountCharacters", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication.UtilityServiceRef.CountCharactersResponse> CountCharactersAsync(WebApplication.UtilityServiceRef.CountCharactersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webstrar.fulton.asu.edu/website142/AddIntegers", ReplyAction="*")]
        int AddIntegers(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webstrar.fulton.asu.edu/website142/AddIntegers", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddIntegersAsync(int a, int b);
        
        // CODEGEN: Generating message contract since element name input from namespace https://webstrar.fulton.asu.edu/website142 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://webstrar.fulton.asu.edu/website142/ReverseString", ReplyAction="*")]
        WebApplication.UtilityServiceRef.ReverseStringResponse ReverseString(WebApplication.UtilityServiceRef.ReverseStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webstrar.fulton.asu.edu/website142/ReverseString", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication.UtilityServiceRef.ReverseStringResponse> ReverseStringAsync(WebApplication.UtilityServiceRef.ReverseStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountCharactersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountCharacters", Namespace="https://webstrar.fulton.asu.edu/website142", Order=0)]
        public WebApplication.UtilityServiceRef.CountCharactersRequestBody Body;
        
        public CountCharactersRequest() {
        }
        
        public CountCharactersRequest(WebApplication.UtilityServiceRef.CountCharactersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webstrar.fulton.asu.edu/website142")]
    public partial class CountCharactersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public CountCharactersRequestBody() {
        }
        
        public CountCharactersRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountCharactersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountCharactersResponse", Namespace="https://webstrar.fulton.asu.edu/website142", Order=0)]
        public WebApplication.UtilityServiceRef.CountCharactersResponseBody Body;
        
        public CountCharactersResponse() {
        }
        
        public CountCharactersResponse(WebApplication.UtilityServiceRef.CountCharactersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webstrar.fulton.asu.edu/website142")]
    public partial class CountCharactersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CountCharactersResult;
        
        public CountCharactersResponseBody() {
        }
        
        public CountCharactersResponseBody(int CountCharactersResult) {
            this.CountCharactersResult = CountCharactersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReverseString", Namespace="https://webstrar.fulton.asu.edu/website142", Order=0)]
        public WebApplication.UtilityServiceRef.ReverseStringRequestBody Body;
        
        public ReverseStringRequest() {
        }
        
        public ReverseStringRequest(WebApplication.UtilityServiceRef.ReverseStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webstrar.fulton.asu.edu/website142")]
    public partial class ReverseStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public ReverseStringRequestBody() {
        }
        
        public ReverseStringRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReverseStringResponse", Namespace="https://webstrar.fulton.asu.edu/website142", Order=0)]
        public WebApplication.UtilityServiceRef.ReverseStringResponseBody Body;
        
        public ReverseStringResponse() {
        }
        
        public ReverseStringResponse(WebApplication.UtilityServiceRef.ReverseStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webstrar.fulton.asu.edu/website142")]
    public partial class ReverseStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReverseStringResult;
        
        public ReverseStringResponseBody() {
        }
        
        public ReverseStringResponseBody(string ReverseStringResult) {
            this.ReverseStringResult = ReverseStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UtilityServiceSoapChannel : WebApplication.UtilityServiceRef.UtilityServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilityServiceSoapClient : System.ServiceModel.ClientBase<WebApplication.UtilityServiceRef.UtilityServiceSoap>, WebApplication.UtilityServiceRef.UtilityServiceSoap {
        
        public UtilityServiceSoapClient() {
        }
        
        public UtilityServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilityServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilityServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilityServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.UtilityServiceRef.CountCharactersResponse WebApplication.UtilityServiceRef.UtilityServiceSoap.CountCharacters(WebApplication.UtilityServiceRef.CountCharactersRequest request) {
            return base.Channel.CountCharacters(request);
        }
        
        public int CountCharacters(string input) {
            WebApplication.UtilityServiceRef.CountCharactersRequest inValue = new WebApplication.UtilityServiceRef.CountCharactersRequest();
            inValue.Body = new WebApplication.UtilityServiceRef.CountCharactersRequestBody();
            inValue.Body.input = input;
            WebApplication.UtilityServiceRef.CountCharactersResponse retVal = ((WebApplication.UtilityServiceRef.UtilityServiceSoap)(this)).CountCharacters(inValue);
            return retVal.Body.CountCharactersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication.UtilityServiceRef.CountCharactersResponse> WebApplication.UtilityServiceRef.UtilityServiceSoap.CountCharactersAsync(WebApplication.UtilityServiceRef.CountCharactersRequest request) {
            return base.Channel.CountCharactersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication.UtilityServiceRef.CountCharactersResponse> CountCharactersAsync(string input) {
            WebApplication.UtilityServiceRef.CountCharactersRequest inValue = new WebApplication.UtilityServiceRef.CountCharactersRequest();
            inValue.Body = new WebApplication.UtilityServiceRef.CountCharactersRequestBody();
            inValue.Body.input = input;
            return ((WebApplication.UtilityServiceRef.UtilityServiceSoap)(this)).CountCharactersAsync(inValue);
        }
        
        public int AddIntegers(int a, int b) {
            return base.Channel.AddIntegers(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddIntegersAsync(int a, int b) {
            return base.Channel.AddIntegersAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.UtilityServiceRef.ReverseStringResponse WebApplication.UtilityServiceRef.UtilityServiceSoap.ReverseString(WebApplication.UtilityServiceRef.ReverseStringRequest request) {
            return base.Channel.ReverseString(request);
        }
        
        public string ReverseString(string input) {
            WebApplication.UtilityServiceRef.ReverseStringRequest inValue = new WebApplication.UtilityServiceRef.ReverseStringRequest();
            inValue.Body = new WebApplication.UtilityServiceRef.ReverseStringRequestBody();
            inValue.Body.input = input;
            WebApplication.UtilityServiceRef.ReverseStringResponse retVal = ((WebApplication.UtilityServiceRef.UtilityServiceSoap)(this)).ReverseString(inValue);
            return retVal.Body.ReverseStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication.UtilityServiceRef.ReverseStringResponse> WebApplication.UtilityServiceRef.UtilityServiceSoap.ReverseStringAsync(WebApplication.UtilityServiceRef.ReverseStringRequest request) {
            return base.Channel.ReverseStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication.UtilityServiceRef.ReverseStringResponse> ReverseStringAsync(string input) {
            WebApplication.UtilityServiceRef.ReverseStringRequest inValue = new WebApplication.UtilityServiceRef.ReverseStringRequest();
            inValue.Body = new WebApplication.UtilityServiceRef.ReverseStringRequestBody();
            inValue.Body.input = input;
            return ((WebApplication.UtilityServiceRef.UtilityServiceSoap)(this)).ReverseStringAsync(inValue);
        }
    }
}
